# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notifypulse < Formula
  desc "Notifypulse CLI — one-API notification relay from the terminal"
  homepage "https://notifypulse.cloudbox.sh"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.3/notifypulse_0.0.3_darwin_x86_64.tar.gz"
      sha256 "9cde9c1e1ab62b4921c5736fcc62d89d0f0cf59114bb49273db15291397516fd"

      define_method(:install) do
        bin.install "notifypulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.3/notifypulse_0.0.3_darwin_arm64.tar.gz"
      sha256 "e658a35f2eee228fa93bd83cabbdb5beafdfa4826d2ef2d5881b92add000253a"

      define_method(:install) do
        bin.install "notifypulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.3/notifypulse_0.0.3_linux_x86_64.tar.gz"
      sha256 "d907c02b02231eb6e9e663e9f9130890eabf257be59472bb4856faa84c64b095"
      define_method(:install) do
        bin.install "notifypulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.3/notifypulse_0.0.3_linux_arm64.tar.gz"
      sha256 "ff0bb2aa06c2ca7b8379d92aa681e92a6b9d7f407be89eab4abd1cdc8100f707"
      define_method(:install) do
        bin.install "notifypulse"
      end
    end
  end

  test do
    system "#{bin}/notifypulse version"
  end
end
