# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notifypulse < Formula
  desc "Notifypulse CLI — one-API notification relay from the terminal"
  homepage "https://notifypulse.cloudbox.sh"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.1/notifypulse_0.0.1_darwin_x86_64.tar.gz"
      sha256 "dd2f8c7e2f47a96bb8633bd53b0d36ad2f9d54f5fb67ff68241ab52b05294a28"

      define_method(:install) do
        bin.install "notifypulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.1/notifypulse_0.0.1_darwin_arm64.tar.gz"
      sha256 "d24934a670158a2fdd7b813ad1154d8ffcbb7706efc12c4ff9bedb984bf039e8"

      define_method(:install) do
        bin.install "notifypulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.1/notifypulse_0.0.1_linux_x86_64.tar.gz"
      sha256 "96a402c70758860f41be3f04ad394eace062fc4256511d8ebc4ce4f3b5b1e9e4"
      define_method(:install) do
        bin.install "notifypulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudbox-sh/notifypulse/releases/download/v0.0.1/notifypulse_0.0.1_linux_arm64.tar.gz"
      sha256 "7f9d1b856d5302c1912ba51416247c5fb94b9da03db1ca9c4aac22d8930f2fcf"
      define_method(:install) do
        bin.install "notifypulse"
      end
    end
  end

  test do
    system "#{bin}/notifypulse version"
  end
end
