# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Statuspulse < Formula
  desc "StatusPulse CLI — hosted status pages from the terminal"
  homepage "https://statuspulse.cloudbox.sh"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudbox-sh/statuspulse/releases/download/v0.0.1/statuspulse_0.0.1_darwin_x86_64.tar.gz"
      sha256 "bc79eac9028db057851b62714bae4fb6b3a45949356a434d15391fd1967d6e3d"

      define_method(:install) do
        bin.install "statuspulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudbox-sh/statuspulse/releases/download/v0.0.1/statuspulse_0.0.1_darwin_arm64.tar.gz"
      sha256 "4a4f555f1773993fbf0fd243518bc18831e8e1da3d336131b502ca582ab55b5b"

      define_method(:install) do
        bin.install "statuspulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudbox-sh/statuspulse/releases/download/v0.0.1/statuspulse_0.0.1_linux_x86_64.tar.gz"
      sha256 "2b19e23b83811371892c4ac7de52f6e81e817b55d5b17c11d36106dd8629203b"
      define_method(:install) do
        bin.install "statuspulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloudbox-sh/statuspulse/releases/download/v0.0.1/statuspulse_0.0.1_linux_arm64.tar.gz"
      sha256 "1cd99ce84f600c60fcb397f3aee3a6a9742e0206646d732873b2aa4e6fd78df2"
      define_method(:install) do
        bin.install "statuspulse"
      end
    end
  end

  test do
    system "#{bin}/statuspulse --version"
  end
end
